
services:
  api:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npx nx build task-manager-be && node dist/apps/task-manager-be/main.js"
    volumes:
      - ./:/app
    ports: ["3000:3000"]
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"
      NODE_ENV: "development"
    restart: unless-stopped

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npx nx serve task-manager-fe --host 0.0.0.0 --port 4200"
    volumes:
      - ./:/app
    ports: ["4200:4200"]
    depends_on: [api]
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"
    restart: unless-stopped